# Example Site settings

#google_analytics: UA-NNNNNNNN-N
title: Yellta's console
url: https://yellTa.github.io/ # root address of the site
description:
  Yellta!입니닷 <br>
  언제나 WHYYYY 라는 생각을 하면서 코딩을 하는 것 같습니다... 그래야 왜 이렇게 돌아가는지...<br>
  내가 어떻게 가이드를 짜야 내가 원하는 대로 코드가 돌아가는지 알 수 있더군요 <br>
  배움은 끝이 없어서 힘들지만 인간으로 태어난 이상 회피할 수는 없는법!...<br>
  앞으로도 열심히 공부해봅시다!<br>

#  Hello i'm Yellta <br>
#  I'm the back-end developer and I always thinking about WHYYYYYYYYYYYY<br>
#  Because that's resource of my Idea<br>
#  make 1 to 1000 YYYYYYYYYYYHEY<br>

header_pages:
  - index.md
#  - about.md
#  - projects.md
  - projects.md
  - posts.md
  - category.md
#  - contact.md

footer: '<a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag


# home variables
pro_cnt: 2
post_cnt: 4